#! /usr/bin/python -u

import pi-telemetry
import logging
import argparse
import os
import rpI2C as i2c


# parse the command-line
parser = argparse.ArgumentParser()
parser.add_argument('-broker', '--mqtt_broker', help='Address of the MQTT broker to send data to', default='mqtt.agdon.net')
parser.add_argument('-base_topic', '--mqtt_base_topic', help='MQTT base topic', default='dev/19c/shed')
parser.add_argument('-l', '--log-level', help="Log level, 'info' or 'debug'", default='debug', choices=['info', 'debug'])
args = parser.parse_args()

# Initialise logging
logging.basicConfig(level = {'info':logging.INFO, 'debug':logging.DEBUG}[args.log_level])
log = logging.getLogger("pi-telemetry")
log.setLevel({'info':logging.INFO, 'debug':logging.DEBUG}[args.log_level])
log.info("pi-telemetry started")
log.debug(args)
mqtt_broker = args.mqtt_broker
mqtt_base_topic = args.mqtt_base_topic

pitelemetry = pi-telemetry.PiTelemetry(mqtt_broker, mqtt_base_topic)
log.debug("pitelemetry = " + str(pitelemetry))
pitelemetry.run()
